### ISSUE TITLE
Link in _index.md is not correct in production environment

### ISSUE THREAD

**Issue by JoeShi** [imfing/hextra#206]
**Description**
The link in `_index.md` is correctly rendered in development environment, but not correct in production environment.

Doc tree
<img width="266" alt="Screenshot 2023-11-15 at 18 34 44" src="https://github.com/imfing/hextra/assets/2173635/8429a39d-c90c-465e-a500-e20a9f76c07f">

**Steps To Reproduce**
1. input `Check out the [installation guide](guide/install/) to get started.` in the `content/docs/_index.md` file
2. run `hugo server --logLevel debug --disableFastRender`, and it can navigate to the path `docs/guide/install/`
3. run `hugo --production`, and it navigate to path `guide/install/` which is wrong.

**Expected Behavior**

**Actual Behavior**

**Screenshots**

**Environment**

- Hugo Version: [e.g., 0.85.0]
- Browser/OS: [e.g., Chrome, MacOS]
- Theme Version: [e.g., v2.0]

**Additional Context**

**Comment by imfing** [comment]
@JoeShi  This sounds weird. Which theme version are you using?

**Comment by JoeShi** [comment]
theme: v0.6.5
hugo: v0.118.2

**Comment by imfing** [comment]
@JoeShi despite following the instructions you've provided, I wasn't able to replicate the problem using Hugo v0.119.0. It's possible that the cause lies elsewhere, as the theme is designed not to alter the default link behavior.

To help isolate the issue, I suggest setting up a fresh environment using the [hextra-starter-template](https://github.com/imfing/hextra-starter-template). 

Could you please try this and let me know if you encounter the same problem?
